/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './date-format.module';
import * as import2 from '@angular/core/src/di/injector';
class DateFormatModuleInjector extends import0.NgModuleInjector<import1.DateFormatModule> {
  _DateFormatModule_0:import1.DateFormatModule;
  constructor(parent:import2.Injector) {
    super(parent,[],[]);
  }
  createInternal():import1.DateFormatModule {
    this._DateFormatModule_0 = new import1.DateFormatModule();
    return this._DateFormatModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.DateFormatModule)) { return this._DateFormatModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DateFormatModuleNgFactory:import0.NgModuleFactory<import1.DateFormatModule> = new import0.NgModuleFactory(DateFormatModuleInjector,import1.DateFormatModule);